version: "3.8"

services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:13
    container_name: sales_analyzer_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sales_analyzer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Banco de dados MongoDB
  mongo:
    image: mongo:5.0
    container_name: sales_analyzer_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Backend (FastAPI)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sales_analyzer_backend
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sales_analyzer
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - MONGO_URI=mongodb://root:root@mongo:27017
      - MONGO_DB=sales_analyzer
      - SECRET_KEY=supersecretkey
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - postgres
      - mongo

  # Frontend (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sales_analyzer_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      - backend

# Volumes para persistência de dados
volumes:
  postgres_data:
  mongo_data:
